FROM debian:buster

ENV OS_IDENTIFIER debian-10
ENV DEBIAN_FRONTEND noninteractive

ARG R_VERSION

RUN apt-get update  
RUN apt-get install -y gdebi-core curl

RUN curl -O https://cdn.rstudio.com/r/debian-10/pkgs/r-${R_VERSION}_1_amd64.deb && gdebi -n r-${R_VERSION}_1_amd64.deb && rm -f r-${R_VERSION}_1_amd64.deb

RUN apt-get install -y git libgsl-dev
COPY run-bench.sh .
ENTRYPOINT ./run-bench.sh

